### ISSUE TITLE
A network error was encountered. Please check your internet connection and try again

### ISSUE THREAD

**Issue by totti4ever** [PantryParty/pantry_party#51] opened 2020-05-06 06:19 UTC
After inserting the API key. The given URL is a local only, but reachable from my Android.

**Comment by arjes** [comment] 2020-05-06 13:02
Thanks for the report.

There have been a few reports of this on reddit. That error indicates the app had it's connecting terminated for odd reasons (status code 0). Are you using http or https?

**Comment by totti4ever** [comment] 2020-05-06 13:07
http

**Comment by mwolfaardt** [comment] 2020-05-06 13:25
same with mine

**Comment by arjes** [comment] 2020-05-06 15:02
I was able to reproduce this in a simulator on Android 10. It looks like at some point android started requiring https connections from apps. I'm going to review the android docs and see if I can do anything to allow these connections.

If it is possible for you to install a LetsEncrypt cert, that should clear it up immediately.

**Comment by totti4ever** [comment] 2020-05-06 15:10
Okay, I just figured out that I actually had setup grocy to listen not only on my local .home domain per http but also on my external domain via https, because otherwise I couldn't use the barcode scanner/camera (Chrome restriction). I had already secured it by an IP filter, so only local IPs are allowed.

So I'm fine now, thanks!

P.S.: Think about donation instead of ads (how much money do you get from ads anyway? I suppose, donating 5€ is worth heaps installations with ads enabled?

**Comment by arjes** [comment] 2020-05-06 17:16
I've pushed a new release for Android which should allow you to connect to non-http endpoints. Let me know if that solves your problem.

As for the ads vs donations option. I honestly don't know the long term CPM of ads or the frequency of donations. I'm about $150 into the project, and apple requires a continuing subscription to continue to publish the app. I would be surprised if I ever recoup the cost, but I figure I'll save that much in groceries every year.

I only included the ads because it is better that I start with ads, then add them later.

**Comment by mwolfaardt** [comment] 2020-05-07 10:52
I see in the appstore the latest version is for 4 May, will your changes become available via the android app store? Also have a look at barcode buddy, they setup integration by scanning a barcode, and it works great

**Comment by arjes** [comment] 2020-05-07 12:39
@mwolfaardt that new version was out yesterday, based on your comment though I'm guessing you don't see it yet. That is odd I did not stage the rollout so it should be available to everyone.

**Comment by mwolfaardt** [comment] 2020-05-08 14:03
Thanks, I've tried again today and it's working

**Comment by arjes** [comment] 2020-05-09 02:51
@mwolfaardt Thanks for reporting back. I'm going to close this but feel free to reopen it if you have further trouble

**Closed by arjes** 2020-05-09 02:51 UTC

**Comment by renannprado** [comment] 2020-07-05 17:54
@arjes 
I face the same error while connecting to my grocy API.

I've installed my home CA in my phone and other apps such as browsers and bitwarden stopped complaining after that, but with Pantry Party I was forced to use HTTP instead of HTTPS in order to use the app.

Would be nice if you can put the actual error message that happened so that it's easier for to report. At the moment I believe that the app is not trusting, for some reason, the CAs that were added by users.

**Comment by arjes** [comment] 2020-07-06 00:11
@renannprado Sorry about that. Unfortunately since this is a Nativescript app I have limited access to some diagnostics and all network level errors tend to show up as simply code 0.

I'll try and re-create it locally and see if the error body is more helpful.
